[versions]
# App version
version-name="1.0.1-hf"
version-code="43"

android = "8.13.1"
kotlin = "2.2.21"
serialization = "2.2.21"
ksp = "2.2.20-2.0.3"
compose-bom = "2025.12.00"
material3-expressive = "1.5.0-alpha10"
constraintlayout-compose = "1.1.1"
activity-compose = "1.12.1"
lifecycle = "2.9.6"
core-ktx = "1.17.0"
appcompat = "1.7.1"
work = "2.11.0"
startup-runtime = "1.2.0"
media3 = "1.8.0"
okhttp3 = "5.3.2"
junit = "4.13.2"
androidx-junit = "1.3.0"
espresso-core = "3.7.0"
room = "2.8.4"
legacy-support-v4 = "1.0.0"
coroutines-android = "1.10.2"
coroutines-guava = "1.10.2"
navigation = "2.9.1"
gson = "2.13.2"
coil3 = "3.3.0"
kmpalette = "3.1.0"
easypermissions = "3.0.0"
datastore-preferences = "1.2.0"
paging = "3.4.0-alpha04"
customactivityoncrash = "2.4.0"
aboutlibraries = "13.1.0"
ktor = "3.3.3"
brotli = "0.1.2"
ksoup = "0.6.0"
desugaring = "2.1.5"
koin-bom = "4.1.1"
md = "0.38.1"
haze = "1.7.1"
smart-exception = "0.2.1"
onetimepassword = "2.4.1"
common = "1.19.0"
json = "1.9.0"
gemini-kotlin = "4.0.2"
slf4j = "1.7.36"
sentry-android = "8.28.0"
sentry-gradle-android = "5.12.2"
sentry-jvm = "8.28.0"
newpipe = "31edd9f7ad2b8e309442e86d5318cc2779480674"
webkit = "1.14.0"
kermit = "2.0.8"
paging-common = "3.3.6"
glance = "1.1.1"
liquid-glass = "1.0.2"
ytdlp = "0.18.1"
ffmpeg-kit-audio="6.0.1"
composeHotReload = "1.0.0"
composeMultiplatform = "1.10.0-rc02"
datetime = "0.7.1"
sqlite = "2.6.2"
okio = "3.16.4"
gst1JavaCore = "1.4.0"
gst1JavaFx = "0.9.0"
gst1JavaSwing = "0.9.0"
material3-multiplatform = "1.10.0-alpha05"
adaptive = "1.2.0"
material-multiplatform = "1.9.3"
material-icons-multiplatform = "1.7.3"
componentsResources="1.10.0-rc02"
foundation="1.10.0-rc02"
runtime="1.10.0-rc02"
compottie = "2.0.2"
cmptoast = "1.0.71"
uri = "0.0.21"
buildkonfig = "0.17.1"
jna="5.18.1"
jnaPlatform="5.18.1"
calf = "0.9.0"
material = "1.13.0"
osdetector = "1.7.3"

[libraries]
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugaring"}
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3-lib = { group = "androidx.compose.material3", name = "material3", version.ref = "material3-expressive" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3-multiplatform" }
compose-material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "adaptive" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "material-multiplatform" }
compose-material-ripple = { group = "org.jetbrains.compose.material", name = "material-ripple", version.ref = "material-multiplatform" }
compose-material-icons-core = { group = "org.jetbrains.compose.material", name = "material-icons-core", version.ref = "material-icons-multiplatform" }
compose-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "material-icons-multiplatform" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
jetbrains-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup-runtime" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media3-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3" }
media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
media3-exoplayer-rtsp = { group = "androidx.media3", name = "media3-exoplayer-rtsp", version.ref = "media3" }
media3-exoplayer-smoothstreaming = { group = "androidx.media3", name = "media3-exoplayer-smoothstreaming", version.ref = "media3" }
media3-exoplayer-workmanager = { group = "androidx.media3", name = "media3-exoplayer-workmanager", version.ref = "media3" }
media3-datasource-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3" }
smart-exception = { module = "com.arthenica:smart-exception-java", version.ref = "smart-exception" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-migration = { module = "androidx.room:room-migration", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy-support-v4" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines-android" }
coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "coroutines-guava" }
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
easypermissions = { group = "pub.devrel", name = "easypermissions", version.ref = "easypermissions" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging"}
customactivityoncrash = { group = "cat.ereza", name = "customactivityoncrash", version.ref = "customactivityoncrash" }
aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries" }
aboutlibraries-compose-m3 = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil3" }
kmpalette-core = { module = "com.kmpalette:kmpalette-core", version.ref = "kmpalette" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-xml = { group = "io.ktor", name = "ktor-serialization-kotlinx-xml", version.ref = "ktor" }
ktor-serialization-kotlinx-protobuf = { group = "io.ktor", name = "ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }
brotli-dec = { group = "org.brotli", name = "dec", version.ref = "brotli" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test"}
ksoup-html = { group = "com.mohamedrejeb.ksoup", name = "ksoup-html", version.ref = "ksoup" }
ksoup-entities = { group = "com.mohamedrejeb.ksoup", name = "ksoup-entities", version.ref = "ksoup" }
markdown = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "md" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-material = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
kotlin-onetimepassword = { module = "dev.turingcomplete:kotlin-onetimepassword", version.ref = "onetimepassword" }
common = { module = "commons-codec:commons-codec", version.ref = "common" }
gemini-kotlin = { module = "org.simpmusic.gemini-kotlin:openai-client", version.ref = "gemini-kotlin" }
logging = { module = "org.slf4j:slf4j-android", version.ref = "slf4j" }
newpipe-extractor = { module = "com.github.teamnewpipe:NewPipeExtractor", version.ref = "newpipe" }
#leak-canary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
kermit-logging = { module = "co.touchlab:kermit", version.ref = "kermit" }
glance = { group = "androidx.glance", name = "glance", version.ref = "glance" }
glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }

liquid-glass = { module = "io.github.kyant0:backdrop", version.ref = "liquid-glass" }

ytdlp-android = { module = "io.github.junkfood02.youtubedl-android:library", version.ref = "ytdlp" }

ffmpeg-kit-audio = { module = "io.github.maxrave-dev:ffmpeg-kit-audio", version.ref = "ffmpeg-kit-audio" }

# KMP
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
uri = { module = "com.eygraber:uri-kmp", version.ref = "uri" }

#CMP
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines-android" }
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
compottie-lite = { module = "io.github.alexzhirkevich:compottie-lite", version.ref = "compottie" }
compottie-dot = { module = "io.github.alexzhirkevich:compottie-dot", version.ref = "compottie" }
compottie-network = { module = "io.github.alexzhirkevich:compottie-network", version.ref = "compottie" }
compottie-resources = { module = "io.github.alexzhirkevich:compottie-resources", version.ref = "compottie" }
cmptoast = { module = "network.chaintech:cmptoast", version.ref = "cmptoast" }
file-picker = { module = "com.mohamedrejeb.calf:calf-file-picker", version.ref = "calf"}

#JVM
gst1-java-core = { module = "org.freedesktop.gstreamer:gst1-java-core", version.ref = "gst1JavaCore" }
gst1-java-fx = { module = "org.freedesktop.gstreamer:gst1-java-fx", version.ref = "gst1JavaFx" }
gst1-java-swing = { module = "org.freedesktop.gstreamer:gst1-java-swing", version.ref = "gst1JavaSwing" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jnaPlatform" }
nowplaying = { module = "org.simpmusic:nowplayingcenter", version = "0.0.1" }
jmtc = { module = "org.simpmusic:jmtc", version = "0.0.1" }

#Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-jvm = { module = "io.insert-koin:koin-core-jvm" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-android = { module = "io.insert-koin:koin-android"}

#Sentry
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentry-android"}
sentry-jvm = { module = "io.sentry:sentry", version.ref = "sentry-jvm"}

androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }

androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging-common" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutlibraries" }
aboutlibraries-multiplatform = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
room = { id = "androidx.room", version.ref = "room" }
sentry-gradle = { id = "io.sentry.android.gradle", version.ref = "sentry-gradle-android" }

# KMP
android-lint = { id = "com.android.lint", version.ref = "android" }
compose-hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
build-config = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }

# JVM
osdetector = { id = "com.google.osdetector", version.ref = "osdetector" }