[versions]
# App version
version-name="0.2.19"
version-code="38"

android = "8.12.0"
kotlin = "2.2.0"
serialization = "2.2.0"
ksp = "2.2.0-2.0.2"
compose-bom = "2025.07.00"
constraintlayout-compose = "1.1.1"
activity-compose = "1.10.1"
lifecycle-viewmodel-compose = "2.9.2"
lifecycle-runtime-ktx = "2.9.2"
core-ktx = "1.16.0"
appcompat = "1.7.1"
work = "2.10.2"
material = "1.12.0"
startup-runtime = "1.2.0"
lifecycle-livedata-ktx = "2.9.2"
lifecycle-viewmodel-ktx = "2.9.2"
ui-tooling = "1.8.3"
media3 = "1.8.0"
okhttp3 = "5.1.0"
palette-ktx = "1.0.0"
expandable-text = "2.0.1"
constraintlayout = "2.2.1"
junit = "4.13.2"
androidx-junit = "1.2.1"
espresso-core = "3.6.1"
room = "2.7.2"
legacy-support-v4 = "1.0.0"
coroutines-android = "1.10.2"
coroutines-guava = "1.10.2"
navigation = "2.9.2"
gson = "2.13.1"
coil3 = "3.3.0"
kmpalette = "3.1.0"
easypermissions = "3.0.0"
preference-ktx = "1.2.1"
fragment-ktx = "1.8.8"
datastore-preferences = "1.1.7"
swiperefreshlayout = "1.2.0-beta01"
insetter = "0.6.1"
lottie = "6.6.7"
paging = "3.3.6"
customactivityoncrash = "2.4.0"
sdp-android = "1.1.1"
ssp-android = "1.1.1"
aboutlibraries = "12.2.4"
flexbox = "3.0.0"
balloon = "1.6.12"
insetsx = "0.1.0-alpha10"
ktor = "3.2.3"
brotli = "0.1.2"
ksoup = "0.6.0"
desugaring = "2.1.5"
koin-bom = "4.1.0"
md = "0.35.0"
store = "5.1.0-alpha06"
ui-text-android = "1.8.3"
haze = "1.6.9"
smart-exception = "0.2.1"
onetimepassword = "2.4.1"
common = "1.19.0"
json = "1.9.0"
gemini-kotlin = "4.0.2"
slf4j = "1.7.36"
sentry-android = "8.17.0"
sentry-gradle = "5.8.0"
newpipe = "7adbc48a0aa872c016b8ec089e278d5e12772054"
leakcanary = "2.14"

[libraries]
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring"}
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3-lib = { group = "androidx.compose.material3", name = "material3" }
compose-material3-sizeclass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material-ripple = { group = "androidx.compose.material", name = "material-ripple" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
work-testing = { group = "androidx.work", name = "work-testing", version.ref = "work" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup-runtime" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "ui-tooling" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media3-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3" }
media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
media3-exoplayer-rtsp = { group = "androidx.media3", name = "media3-exoplayer-rtsp", version.ref = "media3" }
media3-exoplayer-smoothstreaming = { group = "androidx.media3", name = "media3-exoplayer-smoothstreaming", version.ref = "media3" }
media3-exoplayer-workmanager = { group = "androidx.media3", name = "media3-exoplayer-workmanager", version.ref = "media3" }
media3-datasource-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3" }
smart-exception = { module = "com.arthenica:smart-exception-java", version.ref = "smart-exception" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette-ktx" }
expandable-text = { group = "com.github.giangpham96", name = "expandable-text", version.ref = "expandable-text" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy-support-v4" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines-android" }
coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "coroutines-guava" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
easypermissions = { group = "pub.devrel", name = "easypermissions", version.ref = "easypermissions" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
kotlinx-metadata-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-metadata-jvm", version = "0.9.0" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
insetter = { group = "dev.chrisbanes.insetter", name = "insetter", version.ref = "insetter" }
insetter-dbx = { group = "dev.chrisbanes.insetter", name = "insetter-dbx", version.ref = "insetter" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging"}
customactivityoncrash = { group = "cat.ereza", name = "customactivityoncrash", version.ref = "customactivityoncrash" }
sdp-android = { group = "com.intuit.sdp", name = "sdp-android", version.ref = "sdp-android" }
ssp-android = { group = "com.intuit.ssp", name = "ssp-android", version.ref = "ssp-android" }
aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries", version.ref = "aboutlibraries" }
aboutlibraries-compose-m3 = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
balloon = { group = "com.github.skydoves", name = "balloon", version.ref = "balloon" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil3" }
kmpalette-core = { module = "com.kmpalette:kmpalette-core", version.ref = "kmpalette" }
insetsx = { group = "com.moriatsushi.insetsx", name = "insetsx", version.ref = "insetsx" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-xml = { group = "io.ktor", name = "ktor-serialization-kotlinx-xml", version.ref = "ktor" }
ktor-serialization-kotlinx-protobuf = { group = "io.ktor", name = "ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }
brotli-dec = { group = "org.brotli", name = "dec", version.ref = "brotli" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test"}
ksoup-html = { group = "com.mohamedrejeb.ksoup", name = "ksoup-html", version.ref = "ksoup" }
ksoup-entities = { group = "com.mohamedrejeb.ksoup", name = "ksoup-entities", version.ref = "ksoup" }
markdown = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "md" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-material = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
store = { module = "org.mobilenativefoundation.store:store5", version.ref = "store" }
androidx-ui-text-android = { group = "androidx.compose.ui", name = "ui-text-android", version.ref = "ui-text-android" }
kotlin-onetimepassword = { module = "dev.turingcomplete:kotlin-onetimepassword", version.ref = "onetimepassword" }
common = { module = "commons-codec:commons-codec", version.ref = "common" }
gemini-kotlin = { module = "org.simpmusic.gemini-kotlin:openai-client", version.ref = "gemini-kotlin" }
logging = { module = "org.slf4j:slf4j-android", version.ref = "slf4j" }
newpipe-extractor = { module = "com.github.teamnewpipe:NewPipeExtractor", version.ref = "newpipe" }
leak-canary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

#Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-android = { module = "io.insert-koin:koin-android"}

#Sentry
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentry-android"}

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
room = { id = "androidx.room", version.ref = "room" }
sentry-gradle = { id = "io.sentry.android.gradle", version.ref = "sentry-gradle" }