name: Build desktop DMG package

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    paths-ignore:
      - 'README.md'
      - 'fastlane/**'
      - 'assets/**'
      - '.github/**/*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: write

jobs:
  build-desktop-dmg:
    name: Build desktop DMG package
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu"
          cache: 'gradle'

      - name: Update build product flavor
        run: |
          echo "" >> ./gradle.properties
          echo "isFullBuild=true" >> ./gradle.properties

      - name: Update Sentry Secrets
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN_JVM }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          echo 'SENTRY_DSN=${{ secrets.SENTRY_DSN_JVM }}' > ./local.properties
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> ./local.properties

      - name: Generate aboutLibraries.json
        run: ./gradlew exportLibraryDefinitions

      - name: Build desktop DMG package
        run: ./gradlew packageReleaseDmg

      - name: Upload DMG package
        uses: actions/upload-artifact@v4
        with:
          name: desktop-dmg-package
          path: composeApp/build/compose/binaries/main-release/dmg/*.dmg